### ISSUE TITLE
why appliction constructor execute twice?

### ISSUE THREAD

**Issue by loverainstm** [EcsRx/ecsrx.unity#10]
i'm testing the plugin example,why the constructor method of application and EcsRxApplication execute twice?

**Comment by grofit** [comment]
Hey, I don't understand what your question is.

When you use a plugin you just register the plugin in the constructor, which will in turn call through to the plugin and register itself as required, the demo example is shown below.

[Example Plugin Applicaiton File](https://github.com/grofit/ecsrx/blob/master/src/Assets/EcsRx.Examples/PluginExample/Application.cs)

```
using Assets.EcsRx.Examples.PluginExample.HelloWorldPlugin.components;
using EcsRx.Unity;

namespace Assets.EcsRx.Examples.PluginExample
{
    public class Application : EcsRxApplication
    {
        public Application()
        {
            RegisterPlugin(new HelloWorldPlugin.HelloWorldPlugin());
        }

        protected override void GameStarted()
        {
            var defaultPool = PoolManager.GetPool();
            var entity = defaultPool.CreateEntity();
            entity.AddComponent<SayHelloWorldComponent>();
        }
    }
}
```

It should only execute once, and although plugins were put in as a prototype they seemed to work quite well as they are, if you can provide a simple demo or something which shows your problem or you can detail what specifically is happening to you then maybe someone can help more.

**Comment by loverainstm** [comment]
i added debug.log to constructor.
as u  see the attached screenshot. application execute twice when starting and execute once when quiting.
another problem is zenject warning,i think autoregisterinstaller take system resolved and add to systemexcutor should not put in installbinding step.am i right?
![ecsrxlog](https://cloud.githubusercontent.com/assets/7580559/18735388/0deca754-80b0-11e6-86f2-c58afa6b6a07.png)

**Comment by loverainstm** [comment]
i know the reason.it's cause for using constructor in monobehaviour.so it act different from player.
should using awake instead to initialize fields.

**Comment by grofit** [comment]
Will take a look later then, do you have an example project which highlights this as I have not had any warnings so far around what you show above, and generally if you want to inject into MBs you should have an `[Inject]` attribute on an entry method, there is a helper class for this in the project.

[InjectableMonoBehaviour.cs](https://github.com/grofit/ecsrx/blob/master/src/Assets/EcsRx/Unity/MonoBehaviours/InjectableMonoBehaviour.cs)

That there provides you some ECS related objects for free and gives you a MB/Zenject compatible entry point.

As mentioned a code example would be great to see how you are doing it.

**Comment by grofit** [comment]
Hey,

Have just given it a try now on the demo and I do get a 2nd invocation so will look into why it occurs over the weekend.

**Comment by loverainstm** [comment]
i think it's the editor engine problem.so it's best avoid using constructor in monobehaviour.

**Comment by grofit** [comment]
Not entirely sure if `Awake` would be suitable as you need to register the plugins before the DI code is run, so the constructor seemed the best place, I think a virtual method which can be overridden will provide a way for someone to opt in to loading plugins without being forced to like an abstract and sidestep the constructor issue.

**Comment by grofit** [comment]
I have added the notion of `GameStarting` which is run as soon as the underlying `EcsRxApplication` starts doing its stuff, so you can register plugins in there if needed or do anything else you want before the plugins are loaded. I will get this tested and released when I get home later.

**Comment by grofit** [comment]
This should be fixed now, if you look at the example plugin scene you can see there is now a `GameStarting` method you can override and register plugins in there. Thanks for raising it and let me know if you have any other issues.
