### ISSUE TITLE
Scene-first setting up entities based on GOs present in the scene.

### ISSUE THREAD

**Issue by gregee123** [EcsRx/ecsrx.unity#11]
It's kind of related to Issue #8.

It would be nice to see some helper classes or extension methods allowing to attach existing GOs in the scene to entity's ViewComponent.View and subsequently running them through a SetupSystem.

All the above completely programmatically without having to add any Components to the GO manually in Unity Editor.

Also discussed on gitter on 01-Nov-2016.

**Comment by grofit** [comment]
The setting up of ViewComponents View to the GO and applying the EntityView with the applicable entity should be easy, the actual running them through a `SetupSystem` would be a developer concern as you wouldnt know what system it should be run through. As mentioned in chat once the setup has been done, your options for getting the entity picked up by an implementation of `ISetupSystem` is:
- Provide a predicate for the group that the `ISetupSystem` implementation is using (such as checking that the View is not null)
- Create a custom component that indicates these lazy loaded entities have loaded (this would be added after the entity has been applied)
- Only register the system after you have setup all the GOs

Personally I would go with one of the former 2 options, the custom component is slightly simpler but means a dummy component for no reason, the predicate is a slightly more elegant solution but will add observable hooks for each applicable entity, which would slightly increase memory overhead until they are all fulfilled.

**Comment by grofit** [comment]
This should have been implemented as part of the last release, so marking as fixed, if it does not satisfy your use case please re-open.
