### ISSUE TITLE
SystemExecutor doesn't pass Zenject Scene Validation

### ISSUE THREAD

**Issue by gregee123** [EcsRx/ecsrx.unity#13]
SystemExecutor doesn't pass Zenject Scene Validation.

Yes, I know it doesn't prevent EcsRx from running but why not have a Zenject compliant code.

InvalidCastException: Cannot cast from source type to destination type.
Zenject.DiContainer.Resolve[ISystemExecutor] (Zenject.InjectContext context) (at Assets/Zenject/Source/Main/DiContainer.cs:1770)
Zenject.DiContainer.Resolve[ISystemExecutor] (System.Object identifier) (at Assets/Zenject/Source/Main/DiContainer.cs:1723)
Zenject.DiContainer.Resolve[ISystemExecutor] () (at Assets/Zenject/Source/Main/DiContainer.cs:1717)
EcsRx.Unity.Installers.AutoRegisterSystemsInstaller.RegisterSystems () (at Assets/EcsRx/Unity/Installers/AutoRegisterSystemsInstaller.cs:29)
EcsRx.Unity.Installers.AutoRegisterSystemsInstaller.InstallBindings () (at Assets/EcsRx/Unity/Installers/AutoRegisterSystemsInstaller.cs:23)
Zenject.DiContainer.InstallInstallerInternal (IInstaller installer) (at Assets/Zenject/Source/Main/DiContainer.cs:680)
Rethrow as Exception: Error occurred while running installer 'AutoRegisterSystemsInstaller'
Zenject.DiContainer.InstallInstallerInternal (IInstaller installer) (at Assets/Zenject/Source/Main/DiContainer.cs:686)
Zenject.DiContainer.Install (IInstaller installer, IEnumerable`1 extraArgs) (at Assets/Zenject/Source/Main/DiContainer.cs:535)
Zenject.DiContainer.Install (IInstaller installer) (at Assets/Zenject/Source/Main/DiContainer.cs:516)
Zenject.Context.InstallInstallers (System.Collections.Generic.Dictionary`2 extraArgsMap) (at Assets/Zenject/Source/Install/Contexts/Context.cs:158)
Zenject.Context.InstallInstallers () (at Assets/Zenject/Source/Install/Contexts/Context.cs:117)
Zenject.SceneContext.InstallBindings (Zenject.InitialComponentsInjecter componentInjecter) (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:232)
Zenject.SceneContext.RunInternal () (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:183)
Zenject.SceneContext.Run () (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:119)
UnityEngine.Debug:LogException(Exception)
ModestTree.Log:ErrorException(String, Exception) (at Assets/Zenject/Source/Internal/Log.cs:79)
Zenject.SceneContext:Run() (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:129)
Zenject.SceneContext:Awake() (at Assets/Zenject/Source/Install/Contexts/SceneContext.cs:103)

**Comment by grofit** [comment]
As mentioned it seems odd why it would fail and what its actually validating as such within the scene, will look into it but as a lower priority.

**Comment by grofit** [comment]
It seems that #12 is the only issue with scenes, after that is fixed this seems to pass on example scenes.

**Comment by grofit** [comment]
Marking as closed, feel free to re-open if not happy with fix.
