### ISSUE TITLE
System priority documentation

### ISSUE THREAD

**Issue by gregee123** [EcsRx/ecsrx.unity#15]
Please provide some documentation for System priority and how the order of system execution can be determined.

Also please document how to correctly setup system auto binding and registration mentioning if order of namespaces in the list matters

**Comment by grofit** [comment]
Have added documentation on this point, the last bit you mention is a moot point as registration and binding do not occur at the same time, for _most_ scenarios all systems should be registered before entities are, so assuming you are adding entities after systems then it will just handle it as documented and the binding order wont really matter too much.

If you need any additional clarification on anything please re-open.
