### ISSUE TITLE
Entity Ids have finite limit

### ISSUE THREAD

**Issue by grofit** [EcsRx/ecsrx.unity#18]
As I am sure someone else will come out with this at some point, currently the Ids of entities were VERY basic in implementation and will not really track unused ids etc so if you were to instantiate over the period of a game `int.MaxValue` I believe currently it will blow up.

Ids were implemented but the use cases for them seem minimal, so it may be simpler to just remove the notion of Ids, but if there are some good use cases we can do some work around this area to make Ids more intelligent.

**Comment by grofit** [comment]
I have added a fix which will at least not cause exceptions but will just keep looping the ids over, which is not a real solution to the problem.

**Comment by gregee123** [comment]
change the Id to uint or even better ulong?

**Comment by grofit** [comment]
I am not sure if that is compliant in all platforms, and it doesnt solve the problem just gives you a bigger pool to deal with. I think really I need to work out if Ids are needed, as they are not really used for anything.

**Comment by gregee123** [comment]
In C# there's no discrepancy regarding the size and range of integer types.

They are not used cause there's no way to use them. One Cannot find an entity by id.

Id could be useful for example when the system utilizes some sort of serialization and / or DB storage. So more of an MMO / MMORPG thing.

**Comment by grofit** [comment]
its more the "unsigned" bit, I am sure at some point there was some issue with unsigned based vars on different platforms, not sure if it is still a thing.

Anyway the ID stuff was just added as other frameworks had it, given everything is an interface its easy enough for someone who had an MMO style system to implement their own `IEntity`. You can get entities by Id, it would just be via linq, so there is no explicit `GetEntityById` or anything as I have not found a generic use case for it.

So my current thoughts unless I can get some good use-cases for it staying is to remove it and let others who want to have ids on these objects to implement the ids and generators etc themselves.

**Comment by gregee123** [comment]
Linq would need to iterate through the whole List<IEntity> but if there were no use cases in uFrame there probably won't be any here, either.

**Comment by grofit** [comment]
I cannot say that, I never did much complex stuff with uFrame ECS I mainly used MVVM but currently I cannot see any benefits to having them built in. Given that *most* of the time an `id` would be more applicable to a static resource (an item, creature, skill, buff etc) which would generally be done outside the ECS world as its own "library" then consumed within components however makes sense.

Anyway for the moment I will look at removing ids in the next release, however I am happy to do a u-turn and put this on the list if anyone can get me some good examples of why it would be useful to the masses.

**Comment by mrserverless** [comment]
Would it be possible to use a Guid instead of int?

**Comment by grofit** [comment]
Completely and this was a thought as it solves the whole finite problem and the re-use problem, however a guid is 16 bytes I think by default which is 4x that of an int. Maybe it should be done as an interim *fix* to the issue so ids can be used and are all valid, its just I don't know if there would be any performance or data issues with doing this, especially with lots of short lived entities etc.

**Comment by grofit** [comment]
Just to keep everyone in the loop, I have done this on a local branch so it uses Guids, however my laptop screen broke a bit, so I am waiting for it to be returned before I test and commit that branch. So will mark it as in next release but its not technically been comitted yet.
