### ISSUE TITLE
Event raising/handling Issues

### ISSUE THREAD

**Issue by grofit** [EcsRx/ecsrx.unity#19]
To keep the other issues clean and focused I have made this one to discuss changes to event propogation and handling (as mentioned in #17).

The events are mainly there for other things to hook into, as you can make a plugin and put anything into the DI/ECS eco system so some plugins (which track entities or whatever) may want to subscribe to events we would think fairly useless.

Also the issue around components being registered in certain orders shouldnt be an issue, as groups are inclusive, so if you make an entity and add components `A, B, C` or `B ,C A` it doesnt really matter, any systems listening to `A,B` and `B,C` would still trigger. The only thing that may be a hiccup for you would be if you wanted the `B,C` group to be triggered AFTER the `A,B` had been setup, but this is the reason the predicates exist on groups so you can enforce that you not only want Components but also want some state to be true within the entity.

Currently I do not see any problem with the implementation for events but if you can provide specific problem scenarios (and we can then potentially add them to the unit tests), we can see if changes would be needed but currently I don't think you are safe to just assume components will be loaded in a given order, if you do require an order you can use the predicate. The other point about events not being used/needed cause little overhead and make the system more pluggable.

Anyway have a think and if you get together some examples we can look into it further.

**Comment by gregee123** [comment]
So I take it SystemExecutor.OnEntityAddedToPool(EntityAddedEvent args) is only there in case there are systems designed to process completely empty entities which as I've read in another issue may be even stripped of IDs at some point.

**Comment by gregee123** [comment]
I can only suggest that systems expecting no components be kept separately as to not grind through all systems just cause there's a 0.001% chance one of them processes empty entities. It'll speed up creating fresh entities dramatically.

**Comment by grofit** [comment]
The ID bit is unrelated (assuming you mean #18) as it just means that the id count constantly goes up but never re-uses freed up IDs, as it mentions in the story it was a carry over from how other frameworks work but its still an unknown if we need them.

I will for the moment add some checks in so if there is no components on an entity it just wont run any systems, that way other plugins which do care about those events can still make use of empty entities. That should provide a small amount of speed up.

**Comment by grofit** [comment]
A few minor improvements have been made here but I dont think there needs to be much further changed in this area, as even if some of the events are not used right now, they may be later on. Feel free to re-open if you have more to discuss in this area.
