### ISSUE TITLE
Priority values that would put a system at the end of the queue behind the default priority systems.

### ISSUE THREAD

**Issue by gregee123** [EcsRx/ecsrx.unity#21]
So far priority attr can only get a system to be executed before the default, non-prioritized ones.

It would be good to be able to put a system at the and of the queue meaning the priority value of the non-prioritized systems should be known.

**Comment by grofit** [comment]
Will look at getting this added in either next release or the minor after that, as depending on approach taken this may lead to a breaking change (if the term `priority` changes).

**Comment by grofit** [comment]
Flagging this as complete, I have opted to keep priority so it wont cause a breaking change and the terminology seems a better fit. I know it works different to unity but I doubt many people will care, if they do we can revisit this.
