### ISSUE TITLE
IEntity.AddComponent<>() should return the created component

### ISSUE THREAD

**Issue by gregee123** [EcsRx/ecsrx.unity#22]
IEntity.AddComponent<>() should return the created component otherwise it's cumbersome to use unless one just wants to add empty (or tag) components. Maybe this is by design?

**Comment by grofit** [comment]
Ah yes good point, this is how it works for the MB extensions, will add that into a minor release later so IEntity will return the component. I think originally it was assumed you would pass in the component then the generic one was added, and in that case as you say you would want it returned, so will just add the return by default.

**Comment by grofit** [comment]
This should be fixed in 0.7.1 now, re-raise if you are unhappy with implementation.
