### ISSUE TITLE
IReactToDataSystem & IReactToEntitySystem cannot share an implementation class because of method names clash

### ISSUE THREAD

**Issue by gregee123** [EcsRx/ecsrx.unity#25]
ReactToEntity(IEntity entity) == *CLASH*

Seems like it should be ReactToData

**Comment by grofit** [comment]
I think originally it was meant to be like that but it is one of the system types which needs to be removed as its use case is better fulfilled with the `EventReactionSystem` or an `IManualSystem`.

**Comment by gregee123** [comment]
IManualSystem (and by that I also mean EventSystem) doesn't fulfill anything better as it doesn't react do entities being added to the pool. Triggering it manually also doesn't make sense cause it'll just run through all targeted entities and then StartSystem() method needs to sift out the previously processed ones. You can do it with some predicate but it changes nothing effectively.  IManualSystem could be easily replaced with a slightly more elaborate blueprint.

**Comment by grofit** [comment]
`IManualSystem` has huge application, it can be used to manage more complex setup/teardown concerns for things which may not even need entities. As for the event one, it is purely there to act upon events, so it doesnt really care about setup/teardown stuff its currently "best practice" to send all state with an event, so if you have an event where an enemy gets hit, send the attacker, the victim and any other state data in the event. You *can* get groups into it, incase you wanted to do like AoE attacks or something and needed to filter out of the group but generally it is there for specific use cases where you just want to be notified of something, the `IReactToDataSystem` was originally made for this purpose but in reality it is far less useful than these other systems which were created to replace it, and it has been on my todo list for a while to remove it.

You can check out the roguelike example for some `IManualSystem` use cases

**Comment by grofit** [comment]
(I have put this as an enhancement instead of a bug as you can technically still use the current classes/interfaces you just need to add the interface prefix if you want 2 different implementations.)

**Comment by grofit** [comment]
I have found a more niche use case which is better solved by `IReactToDataSystem` than other systems, where you may want to internally react to something on an entity which is treated as an observable but is really an event, anyway making a u-turn on this one and have changed the name to be different so you wont need to use explicit interface hints.

**Comment by grofit** [comment]
This has been released in 0.8.0 feel free to re-open if there are any issues with this
