### ISSUE TITLE
Subscribint to EntityAdded event from SystemExecutor will never serve any purpose.

### ISSUE THREAD

**Issue by gregee123** [EcsRx/ecsrx.unity#30]
Subscribint to EntityAdded event from SystemExecutor will never serve any purpose as those entities are always empty at the time this event is received.

If they weren't empty ( for example if Pool.CreateEntiity() published this event AFTER applying the blueprint) it would be even worse as systems would be applied to entities twice. Once after all required components are added and the second time in response to entity added event.

**Comment by grofit** [comment]
I remember there being possible scenarios for moving entities between pools which would raise the entity created event but not the entity component added event, as well as deserializing (which was not done yet) as that was an unknown if you would just deserialize all the components directly or if you would do them one by one, which I think is why it was originally there (also it supported custom pool implementations which could setup entities differently). Although you are correct that this could introduce an issue where an entity could be picked up twice if someone were to use pre-populated entities, so I will have a think and see if it would be better to leave it as is and just check if an entity has already been added and ignore it if it is the same or just remove this feature as although it supports future use cases if they are not in now its just excess code.

**Comment by gregee123** [comment]
Adding a "ready-made" entity to the pool would certainly be a valid scenario to react to that event but I suspect even then components would need to be re-added which would trigger events anyway.

Unless components would be represented as tables of dynamically typed data and not classes, enabling fully data driven entities but I suppose that's not gonna be in the pipeline anytime soon.

**Comment by grofit** [comment]
I was interested in your discussion on "data driven entities" but you never elaborated further so without seeing some sort of bare bones example of use case/scenario from end to end with that its just words. The only thing I can imagine you mean is basically treating the entity as a huge key/value pair so components act as some sort of veneer on top of that, but if you want some additional features or architectural changes in this area you will NEED to expend some time to write down some examples and how it would be used.

As far as the adding pre-made entity thing goes you shouldn't need to re-create components, if you have already made an entity somewhere and are putting it into a pool then its already populated. I did have a quick go at trying to add some form of generic serialization layer but trying to find serializers which work cross platform in unity and are intelligent enough to just "dump" an object and read it back in.

**Comment by grofit** [comment]
I *think* the new version should fix this, but feel free to re-raise this if its not fixed. (The new version is not due to be released until an rx implementation can be decided upon).
