### ISSUE TITLE
Add collision detection for every entity created by pool

### ISSUE THREAD

**Issue by sviridoff** [EcsRx/ecsrx.unity#44]
I have one scenario, and don't know what is the better form on acomplish the task.
Tha case is , I have a bullet view resolver, that inherit from the **DefaultPooledViewResolverSystem**, I need to add an collision observer to every bullet, to detect collision with enemy (and have the **access to the collided** object in the executor). Basicaly I made this system. But I don't know if there are better ways, if someone have made it differently, I will be very thankful

```
	public class BulletInteractionSystem : IReactToEntitySystem
	{
		private GameObject colliderGO; 

		public BulletInteractionSystem ()
		{
		}

		public IGroup TargetGroup { get { return new Group (typeof(BulletComponent), typeof(ViewComponent)); } }

		public IObservable<IEntity> ReactToEntity(IEntity entity)
		{
			var viewComponent = entity.GetComponent<ViewComponent>();
			return viewComponent.View.OnTriggerEnterAsObservable ()
				.Where(collider => collider.gameObject.tag == "Enemy")
				.Select(collider => {
					colliderGO = collider.gameObject;
					return entity;
				});
		}

		public void Execute(IEntity entity)
		{
			Debug.Log (colliderGO);
			Debug.Log ("trigged");
		}
	}
```

**Comment by grofit** [comment]
Hey,

The title and the content seem to point to different questions being asked, but to tackle the title bit first.

For collision detection to happen there must be a GO in the scene for the collision to act on (generally with a rigidbody and collider of some sort) so as you have done there you need to make sure you have a `ViewComponent` and probably a setup system to setup your views to all have rigidbodies and colliders etc.

To tackle the meat of the question, there are a few different ways to do what you want, so to re-write your code a bit I would probably use an `IReactToDataSystem` which should give you what you need, like so:

```
public class BulletInteractionSystem : IReactToDataSystem
{
	public IGroup TargetGroup { get { return new Group (typeof(BulletComponent), typeof(ViewComponent)); } }

	public IObservable<Collider> ReactToData(IEntity entity)
	{
		var viewComponent = entity.GetComponent<ViewComponent>();
		return viewComponent.View.OnTriggerEnterAsObservable ()
			.Where(collider => collider.gameObject.tag == "Enemy");
	}

	public void Execute(Collider collider, IEntity entity)
	{
        // Do something with the collider and the entity
	}
}
```

This way you can just react to the collision of each entity independently without having to store any sort of state on your system, there could possibly be some better example documentation around system use cases for stuff like this, but hopefully it gives you enough of a route to take with it.

Here is another example of that kind of system from the buffs plugin:
[EffectAddedSystem.cs](https://github.com/grofit/ecsrx.buffs/blob/77c21ae5176a7f577107ed3a407b8d01b306cd0b/Assets/EcsRxPlugins/Buffs/Systems/EffectAddedSystem.cs)

**Comment by grofit** [comment]
Also added a new page in the docs as a starting point to provide some basic "recipes".

https://github.com/grofit/ecsrx/blob/master/docs/common-recipies.md

If you have any other queries feel free to drop into gitter and chat in there.

**Comment by sviridoff** [comment]
Great, it's exactly what I wanted. It was bit annoying to store temporary value to access the collider. Thanks a lot @grofit
