### ISSUE TITLE
IEnumerableExtensions.GetApplicableSystems does not return all applicable systems

### ISSUE THREAD

**Issue by ceinicke** [EcsRx/ecsrx.unity#45]
Line 42 should be "`return systems.Where(x => x.TargetGroup.TargettedComponents.All(y => componentTypes.Contains(y)));`" This way it checks that all targeted components are in the given list of components.

**Comment by Bezarius** [comment]
that's right

**Comment by grofit** [comment]
Been out of the country, just raise a PR for it.

**Comment by grofit** [comment]
Have added a fix for this and a test to verify behaviour for future versions, this will be released in a minor release shortly.
