### ISSUE TITLE
Ambiguous reference to Observable when using Unity with .Net 4.6

### ISSUE THREAD

**Issue by JayPavlina** [EcsRx/ecsrx.unity#48]
If you import into a Unity project using .Net 4.6, you will receive the following error:

`IObservable is an ambiguous reference between System.IObservable<T> and UniRx.IObservable<T>`

The error happens for some examples also.

**Comment by grofit** [comment]
This should be fixed within the [0.10.2 release](https://github.com/grofit/ecsrx/releases/tag/0.10.2), however it still requires the latest unirx to be used with it, as the version on the Asset store/releases doesnt look for the correct pragma variable.
