### ISSUE TITLE
Nits for GroupBuilder

### ISSUE THREAD

**Issue by dxslly** [EcsRx/ecsrx.unity#52]
Howdy there,

I had a couple nit picking comments for GroupBuilder()

1) Add additional constructor that accepts a built IGroup. This would offer a straight forward method to modify an existing Group.
2) GroupBuilder.Create() seems it should be a static factory.
3) Renaming WithComponent() to AddComponent() helps self document its behavior.
4) Renaming WithPredicate() to SetPredicate() helps self document it's behavior.

I didn't notice anything in the readme covering the contribution process (or how you feel about breaking changes :p ), but I would be happy to make a PR.

Cheers,
Dxslly

**Comment by grofit** [comment]
hey hey,

Am always open to PRs, although if it is a breaking change it would ideally go into a branch, but as long as the version released is a major increment doesnt matter too much.

As far as your points go:

1. Fine with this, makes sense
2. Completely makes sense, originally I think I was going to make an interface for further customization, but ended up adding blueprints and didnt go further, so this would make use cases far more succinct.
3. See below
4. I generally prefer the notion of "with" when using builders, as you are not directly adding a group, just telling the builder that the group should be built "with" a component, but will ask in the gitter and get some opinions as I am happy to change it if a few others agree with the `Add/Set` vs `With`.

**Comment by grofit** [comment]
Hello,

So just getting over to this, so...

1) I have allowed you to pass a group to `Create` so you can use that as a template, but it doesn't alter the existing group, it just allows you to use the `Group` to pre-set the internal state.

2) Have made this method static

3/4) Have not renamed anything, after discussion with some other users there was not significant want/need for the name change so for now I am leaving it as `withX` but again if you can get some traction on it I am happy to rethink it.

Hopefull these changes will be in the next version, its only a small update but has a breaking change (the static method) so will be a major release.

**Comment by grofit** [comment]
Release has been done, flagging this as closed for now.
