### ISSUE TITLE
GetUnityComponent does not work with Rigidbody

### ISSUE THREAD

**Issue by OmiCron07** [EcsRx/ecsrx.unity#60]
The extension method GetUnityComponent does not work with the Rigidbody component because it does not inherit of Behavior. The where T of the GetUnityComponent and AddUnityComponent should be changed or removed.

**Comment by grofit** [comment]
I will check this as I think recently this was moved to allow `Behaviour` rather than `MonoBehaviour`, but this should work as you say so if it doesn't its a bug.
