### ISSUE TITLE
The view resolver systems dirived from IViewResolverSystem should in front of system list

### ISSUE THREAD

**Issue by XianWorld** [EcsRx/ecsrx.unity#65]
IEcsRxApplicationExtensions.StartAllBoundSystems line 158, I think ViewResolverSystem should change to IViewResolverSystem interface, so all view resolver derived from IViewResolverSystem will first called to let view ready.

**Comment by grofit** [comment]
Its a tricky one, as in some scenarios you want setup systems to run before the view should be created, and I appreciate in other scenarios its the other way around.

One possible solution here would be to just make `IViewResolverSystem` run as an `ISetupSystem` (as thats what it wraps under the hood) and then you can just use `[Priority(x)]` to stipulate when things should be run.

What are your thoughts? feel free to drop in discord if you want to discuss further.

**Comment by XianWorld** [comment]
In the first, I think I will get the result as I set the [Priority(100)] to my view resolver which is derived from Dynamic one and not from ViewResolverSystem, but I can't let the view resolver run before other system like ViewResolverSystem do, then I read through and debug a lot, but I can't understand what the Priority attribut do. Do you mean If I set the [Priority(100)] to the view resolver, it will at the top of the system list?

**Comment by grofit** [comment]
Hey,

~~Priority works with the lower the number being the earlier it runs, so a priority of 1 would run before a priority of 10. You can also use negative priorities with 0 acting as the "default priority".~~ (The logic around priority has changed a few times so after developer discussion we decided on the following)

Priority works with the higher number being the earlier it is run, so a priority of 100 would run before 1 with 0 being the default, then a priority of -1 would be run AFTER default systems and a -100 would be run after that.

If you look here at the comment it gives examples:
https://github.com/EcsRx/ecsrx/blob/master/src/EcsRx/Attributes/PriorityAttribute.cs

**Comment by grofit** [comment]
Will mark this as closed as in the newer versions a view resolver system is just an `ISetupSystem` with extra guff on it, so it should be run on same priority as other setup systems out the box unless you override it, feel free to re-open if you want to discuss more.
